### PR TITLE
Fixes #66: skip empty resource folder when scanning

### LINKED ISSUE #66: dandelionFilter failed to start when there's an empty resource folder
```
Exception starting filter dandelionFilter
java.lang.NullPointerException: null
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:167) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:175) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:175) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:175) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.scanForResourcePaths(WebResourceScanner.java:146) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.findResourcePath(WebResourceScanner.java:72) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.bundle.loader.support.BowerPreLoader.getExtraBundles(BowerPreLoader.java:121) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.initBundleStorage(Context.java:451) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.init(Context.java:154) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.<init>(Context.java:131) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.web.DandelionFilter.init(DandelionFilter.java:96) ~[dandelion-core-1.1.0.jar:na]
```

### PR DESCRIPTION
**Pull request by wmh**

### CODE REVIEW

**Comment by tduchateau** [comment]
LGTM.
Before merging, could you please read and sign the [ICLA](https://docs.google.com/forms/d/1-lciVTM3cqkcOVmDWH4wEzqE36BNlldtwMaoRUOhHTc/viewform)?
Thanks!

**Comment by wmh** [comment]
Submitted :+1:

**Comment by tduchateau** [comment]
Can one of the admins verify this patch?

**Comment by tduchateau** [comment]
ok to test

**Comment by tduchateau** [comment]
ok to test

**Comment by tduchateau** [comment]
Sorry @wmh, I'm testing the PR builder Jenkins plugin :-)

**Comment by tduchateau** [comment]
Thanks!

**Pull request merged**
