### PR TITLE
Document IE Conditional Comments support

### PR DESCRIPTION
**Pull request by pioto**
This change was introduced in Issue #20, but wasn't documented (I only found it by googling and seeing the issue).

### CODE REVIEW

**Comment by tduchateau** [comment]
Before I can merge your PR, could you please read and sign the ICLA? https://docs.google.com/forms/d/1-lciVTM3cqkcOVmDWH4wEzqE36BNlldtwMaoRUOhHTc/viewform
Thanks!

**Comment by tduchateau** [comment]
Can one of the admins verify this patch?

**Comment by pioto** [comment]
@tduchateau - I've signed the ICLA.

**Comment by tduchateau** [comment]
Thanks!

**Pull request merged**
